#!/bin/sh

#setbg 

autostart="xcompmgr dunst"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

#xrandr --output HDMI-0 --mode 1920x1080 --rate 240
#xrandr --output eDP --set TearFree on
setxkbmap -layout us,ua,ru  -option grp:alt_shift_toggle,caps:escape
