[manager]
show_hidden = true
show_symlink = true

[opener]
pdf_reader = [
	{run = 'sioyek "$@"', orphan = true, for = "unix", block = false}
]

[open]
prepend_rules = [
	{ name = "*.pdf", use = "pdf_reader" },
]
